site_name: OpenFormicaria
nav:
    - Home: index.md
    - About: about.md
    - "User Guide":
       - Getting Started: getting_started.md
       - Connectors: connectors.md
       - Modules: modules.md
       - Formicaria: formicaria.md
    - Contribute: 
        - How to contribute: contrib.md
    - License: license.md
theme:
  features:
    - navigation.instant
  name: material
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/github
    logo: material/ladybug
repo_url: https://github.com/schemen/OpenFormicaria
repo_name: schemen/OpenFormicaria
